dinavid/photos/urls.py
from django.conf.urls import url

from . import views
app_name = 'photos'
urlpatterns = [
    url(r'^clear/$', views.clear_database, name='clear_database'), #Clear the database of list of items
    url(r'^clearresults/$', views.clear_results, name='clear_results'), #Clear list of segmentation results
    url(r'^basic-upload/$', views.BasicUploadView.as_view(), name='basic_upload'), #Basic upload page. Deprecated
    url(r'^progress-bar-upload/$', views.ProgressBarUploadView.as_view(), name='progress_bar_upload'), #Upload page with progress bar. Deprecated
    url(r'^drag-and-drop-upload/$', views.DragAndDropUploadView.as_view(), name='drag_and_drop_upload'),#Upload page with drag and drop bar. Deprecated
    url(r'^tool_intro/$', views.IntroView.as_view(), name='tool_intro'), # tools intro page
    url(r'^visualdisplay/$', views.VisualDisplayView.as_view(), name='visualdisplay'), #3d Display
    url(r'^clearinputvisual/$', views.clear_visual_input, name='clear_visual_input'),
    url(r'^print_sequal/$', views.print_sequal, name='print_sequal'),
    url(r'^csv/$', views.export_users_csv, name='export_users_csv'),     #exporting url with dummy data
    url(r'^workflow_test/$', views.WorkflowTestView.as_view(), name='workflow_test'),   #download page, under folder workflow/index
    url(r'^workflow_compact/$', views.WorkflowCompactView.as_view(), name='workflow_compact'),   #download page, under folder workflow/index
    url(r'^workflow_analysis/$', views.workflow_analysis, name='workflow_analysis'), 
    url(r'^workflow_preview/$', views.workflow_preview, name='workflow_preview'), #Preview the the preprocessing
    url(r'^workflow_process/$', views.workflow_process, name='workflow_process'),  #Actually perform the preprocessing
    url(r'^workflow_seg_preview/$', views.workflow_seg_preview, name='workflow_seg_preview'), #Preview the segmentation
    url(r'^workflow_seg/$', views.workflow_seg, name='workflow_seg'), #Actually perform the segmentation
    url(r'^workflow_quantification/$', views.workflow_quantification, name='workflow_quantification'), #draw_scatter plot
    url(r'^workflow_quantification_preview/$', views.workflow_quantification_preview, name='workflow_quantification_preview'), #draw_scatter plot on subvolume
    url(r'^update_workflow_quantification/$', views.update_workflow_quantification, name='update_workflow_quantification'), #draw_scatter plot
    url(r'^update_workflow_quantification_preview/$', views.update_workflow_quantification_preview, name='update_workflow_quantification_preview'), #draw_scatter plot on subvolume
    url(r'^update_channel_color/$', views.update_channel_color, name='update_channel_color'), #update the color channels
    url(r'^update_channel_name/$', views.update_channel_name, name='update_channel_name'),  # update user's input for channel name
	url(r'^load_channel_names/$', views.load_channel_names, name='load_channel_names'),  # load LUT
    url(r'^update_channel_params/$', views.update_channel_params, name='update_channel_params'),  # update user's input for selector parameters
    url(r'^load_channel_params/$', views.load_channel_params, name='load_channel_params'),  # load LUT
    url(r'^save_channel_params/$', views.save_channel_params, name='save_channel_params'),  # save LUT	
    url(r'^select_image_display/$', views.select_image_display, name='select_image_display'), #Select image to display
    url(r'^visualization_3d/$', views.visualization_3d, name='visualization_3d'),#renders a subregion in 3D
    url(r'^update_channel_color_slice/$', views.update_channel_color_slice, name='update_channel_color_slice'), #update the color channels slice by slice instead of doing all at a time.
    url(r'^zoom_in/$', views.zoom_in, name='zoom_in'), #Used for zoom function
    url(r'^zoom_in_cropped/$', views.zoom_in_cropped, name='zoom_in_cropped'), #Used for zoom function
    url(r'^lut_preprocess/$', views.lut_preprocess, name='lut_preprocess'), #Used for applying an LUT to preprocessed results
    url(r'^lut_preprocess_preview/$', views.lut_preprocess_preview, name='lut_preprocess_preview'), #Used for applying an LUT to preprocessed results
    url(r'^refresh_seg_subwindow/$', views.refresh_seg_subwindow, name='refresh_seg_subwindow'), #Update the window to preview segmentation in real time.
    url(r'^update_max_projection/$', views.update_max_projection, name='update_max_projection'), #Update the maximum intensity projection in real time
    url(r'^psuedo_3d/$', views.Psuedo3dView.as_view(), name='psuedo_3d'),
    url(r'^gen_rot_color_images/$', views.gen_rot_color_images, name='gen_rot_color_images'),   #generate the 360 view for a certain image
    url(r'^demo_index/$', views.DemoView.as_view(), name='demo_index'),   #download page, under folder workflow/index
    url(r'^update_channel_color_demo/$', views.update_channel_color_demo, name='update_channel_color_demo'),   #download page, under folder workflow/index
    url(r'^select_volume/$', views.SelectVolumeView.as_view(), name='select_volume'),  #Used to select which volume to display/process
    url(r'^getting_started/$', views.GetStartedView.as_view(), name='getting_started'), #intro page
    url(r'^upload_segmentation/$', views.upload_segmentation, name='upload_segmentation'), #upload segmentation to server
]

dinavid/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.urls import path
from django.views.generic import TemplateView
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    path(r'', TemplateView.as_view(template_name='home.html'), name='home'),
    path(r'photos/', include('dinavid.photos.urls')),
    path('admin/', admin.site.urls),
    path(r'login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), {'template_name': 'login.html'}, name='login'),
    path(r'logout/', auth_views.LogoutView.as_view(), {'template_name': 'logged_out.html'}, name='logout'),
	path(r'contact/', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dinavid/photos/forms.py
from django import forms

from .models import Photo


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('file', )

dinavid/photos/views.py
import os
import sys

import time
from dinavid.photos import test_all_pad
from datetime import datetime

from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from django.views import View
from .forms import PhotoForm
from .models import Photo, Result, Visual, VisualInput, PreprocessResult
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from dinavid.photos.test_all_pad import *

from django.urls import reverse
import zipfile
from django.core.files import File
import shutil
import json
import subprocess
from dinavid.photos.CC2 import CC2
# visualization
from dinavid.photos.tileImages import tileImages
from dinavid.photos.tileImages_input import tileImages_input, tileImages_input_dropdown, tileImages_input_workflow
from dinavid.photos.writeJSON import writeJSON
from dinavid.photos.copyFiles import copyFiles
from dinavid.photos.writeJSON_input import writeJSON_input
from dinavid.photos.copyFiles_input import copyFiles_input
# timezone
from pytz import timezone
import math
import stat
import glob

from .tasks import celery_process, make_visual_celery, make_visual_celery_dropdown, make_visual_celery_dropdown_nuc, make_visual_celery_workflow, delete_extra_copy, clean_up_folder, delete_extra_copy_pre, remove_orig_files
from celery.result import AsyncResult
######## background subtract ############
from dinavid.photos.background_subtractor import subtract_background_rolling_ball

#dummy data to exporting to csv
import csv
from django.contrib.auth.models import User


#composite images
import tifffile as tiff
import cv2
import numpy as np
import re
import copy

from dinavid.photos.segment_options import segment_3d_watershed, segment_deepsynth, segment_3d_watershed_preview, segment_deepsynth_preview, segment_layercake, segment_layercake_preview, segment_nisnet_preview, segment_nisnet, segment_cellpose_preview, segment_cellpose

from dinavid.photos.scatter_plot import scatter_plot


#Used paths
from dinavid.photos.path_names import *
from dinavid.photos.dinavid_options import *

from django.http import HttpResponseRedirect


#Unzip a zipped folder
def unzip(source_filename, dest_dir):
	with zipfile.ZipFile(source_filename) as zf:
		zf.extractall(dest_dir)

#Find the X,Y dimension of a focal plane/slice.
def findsize(path_image):
	file_base = None
	kk = 0;
	for dirname, subdirs, files in os.walk(path_image):
		for filename in sorted(files):
			# We need only one image
			if (kk > 0):
				break;
			if file_base is None:
				file_base = filename[:-10]
			filepath = os.path.join(dirname, filename);
			I = io.imread(filepath);
			# Check whether it is color or gray image
			if (len(np.shape(I)) == 2):
				[Y, X] = np.shape(I);
				boolColor = 0;
			elif (len(np.shape(I)) > 2):
				[Y, X, _] = np.shape(I);
				boolColor = 1;
			kk = kk + 1;
	return X, Y

#Call to a celery process of the preprocessing steps.
def celeryprocess(request, modelname, colorcode,x1,x2,y1,y2,thSmall,watershed,dataselect,nuc_channel_in,seg_dilate,segdilate_se_size):
	tz = timezone('US/Eastern')
	datetime_now = datetime.now(tz).strftime('%Y-%m-%d-%H-%M-%S')

	user = request.user
	uname = user.username
	if not uname or uname.isspace():
		 uname = 'default'

	original_data_address = HOME_MEDIA_PATH + uname + '/data/'
	## Need to edit here to enable selection of nuclei channel and take the data from /stack
	visual_zip_temp = HOME_MEDIA_PATH + uname + '/preprocess_temp/'

	if not os.path.exists(visual_zip_temp):
		os.makedirs(visual_zip_temp)

	## let the user select which data to use, preprocessed or original
	if dataselect == "orig_data":
		input_address = original_data_address
	else:
		unzip(HOME_MEDIA_PATH+ dataselect, visual_zip_temp)
		input_address = visual_zip_temp

	copy_address = HOME_MEDIA_PATH + uname + '/'


	##copy all file in user folder to remote machine
	subprocess.call(['scp', '-r', input_address, '{}@{}:{}'.format(REMOTE_ACCOUNT_NAME, REMOTE_ADDRESS, copy_address)])
  
	#To add the choice for dilate the result
	mytask = celery_process.delay(nuc_channel_in,input_address,modelname,uname,x1,x2,y1,y2,colorcode,datetime_now,thSmall,watershed,seg_dilate,segdilate_se_size)
	mytask.get()
	
	if colorcode =="YES":
		path = HOME_MEDIA_PATH+uname+'/color_coded/'
	else:
		path = HOME_MEDIA_PATH+uname+'/cc_small_removed/'


	visual_name = HOME_MEDIA_PATH+uname+'/visualization/visual_' + datetime_now + '/'
	visual_copy = HOME_MEDIA_PATH+uname+'/visualization/'
	if not os.path.exists(visual_name):
		os.makedirs(visual_name)

	subprocess.call(['scp', '-r', '{}@{}:{}'.format(REMOTE_ACCOUNT_NAME, REMOTE_ADDRESS, visual_name), visual_copy])

	address_fake = VIZ_3D_ADDRESS
	#address_fake does not matter

	zipfilename = HOME_MEDIA_PATH+uname+'/results_'+ datetime_now +'.zip' 
	zipfilename_copy = HOME_MEDIA_PATH+uname+'/'   
 
	subprocess.call(['scp', '{}@{}:{}'.format(REMOTE_ACCOUNT_NAME, REMOTE_ADDRESS, zipfilename), zipfilename_copy])

	f = open(zipfilename)
	os.remove(zipfilename)

	mytask_delete = delete_extra_copy.delay(colorcode,path,uname,zipfilename)
	mytask_delete.get()

	if dataselect != "orig_data":
		shutil.rmtree(visual_zip_temp)

#Generate 3D visualization for processing steps. 
#This is the version currently in use.
def make_visual_dropdown_nuc(nuc_channel_in, request, x1, x2, y1, y2, operation, resolution, k_size,  \
	sigma, threshtype, threshold, morph_type, se_type, se_size, ball_size, mediankernel,mediansubkernel, num_z, num_ch):
	
	tz = timezone('US/Eastern')
	datetime_now = datetime.now(tz).strftime('%Y-%m-%d-%H-%M-%S')
	user = request.user
	uname = user.username
	
	if not uname or uname.isspace():
		uname = 'default'
	
	original_data_address = HOME_MEDIA_PATH + uname + '/data/orig/'
	visual_temp = HOME_MEDIA_PATH + uname + '/visual_temp/'
	
   
	if not os.path.exists(visual_temp):
		os.makedirs(visual_temp)
	
	#Clean up original folder
	#mytask_delete = clean_up_folder.delay(uname)
	#mytask_delete.get()

	print("task deleted finished")
	input_address = HOME_MEDIA_PATH + uname + '/data/orig'
		
	visual_input_folder = HOME_MEDIA_PATH+uname+'/visualization_input/'
	visual_input_name = HOME_MEDIA_PATH+uname+'/visualization_input/preprocess_visual_' + datetime_now + '/'
   
	preprocess_download = HOME_MEDIA_PATH+uname+'/preprocess/'

	preprocess_url = HOME_MEDIA_PATH+uname+'/preprocess_url/'
	preprocess_url_storage = HOME_MEDIA_PATH+uname+'/preprocess_url_storage/'
	preprocess_orig_to_compare = HOME_MEDIA_PATH+uname+'/preprocess_orig/'
	
	if not os.path.exists(visual_input_name):
		os.makedirs(visual_input_name)
	recursive_file_permissions(visual_input_name,0o775)  
	
	if os.path.exists(preprocess_download):
		shutil.rmtree(preprocess_download)
	if not os.path.exists(preprocess_download):
		os.makedirs(preprocess_download)	
	recursive_file_permissions(preprocess_download,0o775)  

	if not os.path.exists(preprocess_url):
		os.makedirs(preprocess_url)		
	recursive_file_permissions(preprocess_url,0o775)  

	if not os.path.exists(preprocess_url_storage):
		os.makedirs(preprocess_url_storage)   
	recursive_file_permissions(preprocess_url_storage,0o775)  


	print("start delay")
	#Copy from web server to GPU machine.
	copy_address = HOME_MEDIA_PATH + uname + '/'

	W, H, Z, fnamenew, downsample_W, downsample_H = make_visual_celery_dropdown_nuc(nuc_channel_in,uname,datetime_now, visual_input_name, preprocess_download, original_data_address, x1, x2, y1, y2, operation, resolution, k_size,  \
		sigma, threshtype, threshold, morph_type, se_type, se_size, ball_size, mediankernel,mediansubkernel, num_z, num_ch,preprocess_orig_to_compare)
		
		
	#Copy JSON file with image name and dimension
	writeJSON_input(W/downsample_W,H/downsample_H,Z,visual_input_name);
	#Copy visual3d.js and test.html file
	copyFiles_input(visual_input_name);
	
	address_fake = VIZ_3D_ADDRESS

	process_folder = HOME_MEDIA_PATH+uname+'/' 

	zipfilename_pre = preprocess_url_storage +'preprocess_' + datetime_now +'_'+ fnamenew +'.zip' 


	if os.path.exists(visual_temp):
		shutil.rmtree(visual_temp)
	return zipfilename_pre

#Intro page
class IntroView(View):   

	def get(self, request):

		return render(self.request, 'photos/tool_intro/index.html')
 
#Getting started page
class GetStartedView(View):   

	def get(self, request):

		return render(self.request, 'photos/tool_intro/get_started.html')
  
 
#Contact page  
class WebContact(View):   

	def get(self, request):

		return render(self.request, 'photos/tool_intro/contact.html')

#Used for display single 3D on a single page
class VisualDisplayView(View):

	def get(self, request):

		return render(self.request, 'photos/visualdisplay/index.html',{'uname':request.user.username, 'address':VIZ_3D_ADDRESS})


	def post(self, request):
		disname = request.POST['disname'] 
		
		return render(self.request, 'photos/visualdisplay/index.html', {'disname': disname, 'uname':request.user.username,'address':VIZ_3D_ADDRESS})


class BasicUploadView(View):


	def get(self, request):

		# photos_list = Photo.objects.all()
		photos_list = Photo.objects.filter(user=request.user)

		return render(self.request, 'photos/basic_upload/index.html', {'photos': photos_list})

	def post(self, request):
		form = PhotoForm(self.request.POST, self.request.FILES)
		if form.is_valid():
			photo = form.save(commit=False)
			photo.user = request.user
			photo.save()
			data = {'is_valid': True, 'name': photo.file.name, 'url': photo.file.url}
		else:
			data = {'is_valid': False}
		return JsonResponse(data)


class ProgressBarUploadView(View):
	def get(self, request):
		photos_list = Photo.objects.filter(user=request.user, iszip=False)
		return render(self.request, 'photos/progress_bar_upload/index.html', {'photos': photos_list})

	def post(self, request):
		time.sleep(1)  # You don't need this line. This is just to delay the process so you can see the progress bar testing locally.
		form = PhotoForm(self.request.POST, self.request.FILES)
		if form.is_valid():

dinavid/templates/includes/header.html
<script>
function show_not_logged_in()
{
alert("You are not logged in. Please log in to access this page.")
}
</script>

<nav class="navbar navbar-default">
  <div class="container" >
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    
    <a class="navbar-brand" href="{% url 'home' %}"><font size=3>DINAVID</font></a>
    <a class="navbar-brand" href="{% url 'home' %}"><font size=3>Home</font></a>
    <div class="collapse navbar-collapse" id="main-menu" style="height:65px">
      <ul class="nav navbar-nav" style="height:65px">
        <li{% if '/photos/workflow/' in request.path %} class="active"{% endif %} >
          <a style="margin-left: 5px" class="navbar-brand" href="{% url 'photos:getting_started' %}" {% if not user.is_authenticated %} onclick="show_not_logged_in()" {%endif%}><font color = #B03A2E size=3>Getting<br>Started</font></a>
        </li>
        <li{% if '/photos/workflow/' in request.path %} class="active"{% endif %} >
          <a style="margin-left: 5px" class="navbar-brand" href="{% url 'photos:select_volume' %}"><font color = #B03A2E size=3 {% if not user.is_authenticated %} onclick="show_not_logged_in()" {%endif%}>Analysis<br>System</font></a>
        </li>
        <li{% if '/photos/tool_intro/' in request.path %} class="active"{% endif %}>
          <a style="margin-left: 5px" class="navbar-brand" href="{% url 'photos:tool_intro' %}"><font color = #B03A2E size=3 {% if not user.is_authenticated %} onclick="show_not_logged_in()" {%endif%}>Tutorial</font></a>
        </li> 
        

        <li{% if '/photos/contact/' in request.path %} class="active"{% endif %}>
          <a style="margin-left: 5px" class="navbar-brand" href="{% url 'contact' %}"><font color = #B03A2E size=3 > Contact</font></a>
        </li> 
        <li>
           <a style="margin-left: 5px" class="navbar-brand" > Version 5.4.25,<br>Aug 17, 2023      </a>
        </li>
      </ul>
      <div id="auth_div" style="float:right; width=400px">
      {% if user.is_authenticated %}
        <font size=3 face="verdana">User: {{ user.username }} <a href="{% url 'logout' %}">logout</a></font>
      {% else %}
        <font size=3 face="verdana"><a href="{% url 'login' %}">login</a></font>
      {% endif %}
        <!--<p style="font-size:11px">&copy; Copyright 2022 - The Board of Trustees <br> of Purdue University - All rights reserved</p>
      -->
      </div>
    </div>
  </div>
</nav>

dinavid/templates/includes/header_compact.html
<script>
function show_not_logged_in()
{
alert("You are not logged in. Please log in to access this page.")
}
</script>

<nav class="navbar navbar-default">
  <div class="container" >
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    
    <a class="navbar-brand" href="{% url 'home' %}"><font size=3>DINAVID</font></a>
    <a class="navbar-brand" href="{% url 'home' %}"><font size=3>Home</font></a>
    <div class="collapse navbar-collapse" id="main-menu" style="height:65px">
      <ul class="nav navbar-nav" style="height:65px">
        <li{% if '/photos/workflow/' in request.path %} class="active"{% endif %} >
          <a style="margin-left: 5px" class="navbar-brand" href="{% url 'photos:getting_started' %}" {% if not user.is_authenticated %} onclick="show_not_logged_in()" {%endif%}><font color = #B03A2E size=3>Getting<br>Started</font></a>
        </li>
        <li{% if '/photos/workflow/' in request.path %} class="active"{% endif %} >
          <a style="margin-left: 5px" class="navbar-brand" href="{% url 'photos:select_volume' %}"><font color = #B03A2E size=3 {% if not user.is_authenticated %} onclick="show_not_logged_in()" {%endif%}>Analysis<br>System</font></a>
        </li>
        <li{% if '/photos/tool_intro/' in request.path %} class="active"{% endif %}>
          <a style="margin-left: 5px" class="navbar-brand" href="{% url 'photos:tool_intro' %}"><font color = #B03A2E size=3 {% if not user.is_authenticated %} onclick="show_not_logged_in()" {%endif%}>Tutorial</font></a>
        </li> 
        

        <li{% if '/photos/contact/' in request.path %} class="active"{% endif %}>
          <a style="margin-left: 5px" class="navbar-brand" href="{% url 'contact' %}"><font color = #B03A2E size=3 > Contact</font></a></li> 
        <li>
           <a style="margin-left: 5px" class="navbar-brand" > Version 5.4.25,<br>Aug 17, 2023      </a>
        </li>
      </ul>
      <div id="auth_div" style="float:right; width=400px">
      {% if user.is_authenticated %}
        <font size=3 face="verdana">User: {{ user.username }} <a href="{% url 'logout' %}">logout</a></font>
      {% else %}
        <font size=3 face="verdana"><a href="{% url 'login' %}">login</a></font>
      {% endif %}
        <!--<p style="font-size:11px">&copy; Copyright 2022 - The Board of Trustees <br> of Purdue University - All rights reserved</p>
      -->
      </div>
    </div>
  </div>
</nav>